# Generated by Django 4.2.7 on 2023-12-12 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('user_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      to=settings.AUTH_USER_MODEL)),
                ('adopter_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'Adopter',
                'managed': False,
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='AdoptionOrganization',
            fields=[
                ('user_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      to=settings.AUTH_USER_MODEL)),
                ('ao_id', models.AutoField(primary_key=True, serialize=False)),
                ('ao_street', models.CharField(max_length=100)),
                ('ao_country', models.CharField(max_length=50)),
                ('ao_city', models.CharField(max_length=50)),
                ('ao_state', models.CharField(max_length=50)),
                ('total_donation_received', models.IntegerField(default=0)),
                ('total_grants_received', models.IntegerField(default=0)),
                ('total_donators', models.IntegerField(default=0)),
                ('pet_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'AdoptionOrganization',
                'managed': False,
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('user_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      to=settings.AUTH_USER_MODEL)),
                ('vet_id', models.AutoField(primary_key=True, serialize=False)),
                ('vet_street', models.CharField(max_length=100)),
                ('vet_country', models.CharField(max_length=50)),
                ('vet_city', models.CharField(max_length=50)),
                ('vet_state', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Veterinarian',
                'managed': False,
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('adopter_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='main.adopter')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.adopter',),
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('blogger_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='main.blogger')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.blogger',),
        ),
    ]
