# Generated by Django 4.2.7 on 2023-12-17 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('blogger_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Blogger',
                'managed': False,
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('expert_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Expert',
                'managed': False,
            },
            bases=('authentication.user',),
        ),
    ]
