# Generated by Django 4.2.7 on 2023-12-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('ddate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Donation',
                'managed': False,
            },
        ),
    ]
