# Generated by Django 4.2.7 on 2023-12-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateTimeField(auto_now_add=True)),
                ('aapp_file', models.BinaryField(null=True)),
                ('aapp_status', models.CharField(default='PENDING', max_length=8)),
                ('aapp_response_date', models.DateTimeField(null=True)),
                ('amotivation_text', models.TextField(null=True)),
            ],
            options={
                'db_table': 'AdoptionApplication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('breed_id', models.AutoField(primary_key=True, serialize=False)),
                ('breed_name', models.CharField(max_length=100, unique=True)),
                ('intelligence', models.IntegerField()),
                ('playfulness', models.IntegerField()),
            ],
            options={
                'db_table': 'Breed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('ex_id', models.AutoField(primary_key=True, serialize=False)),
                ('ex_description', models.TextField()),
                ('ex_file', models.BinaryField(null=True)),
            ],
            options={
                'db_table': 'Examination',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pet_image', models.CharField(max_length=100)),
                ('pet_color', models.CharField(max_length=50)),
                ('is_adopted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation', models.AutoField(primary_key=True, serialize=False)),
                ('rv_date', models.DateTimeField()),
                ('reasoning', models.TextField()),
                ('rv_status', models.CharField(max_length=8)),
                ('rv_response_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_restricted', models.BooleanField(default=True)),
                ('schedule_beginning_date', models.DateField()),
                ('schedule_end_date', models.DateField()),
            ],
            options={
                'db_table': 'Schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_reserved', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
            ],
            options={
                'db_table': 'Slot',
                'managed': False,
            },
        ),
    ]
