# Generated by Django 4.2.7 on 2023-12-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateTimeField(auto_now_add=True)),
                ('aapp_file', models.BinaryField(null=True)),
                ('aapp_status', models.CharField(default='PENDING', max_length=8)),
                ('aapp_response_date', models.DateTimeField(null=True)),
                ('amotivation_text', models.TextField(null=True)),
            ],
            options={
                'db_table': 'AdoptionApplication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('breed_id', models.AutoField(primary_key=True, serialize=False)),
                ('breed_name', models.CharField(max_length=100, unique=True)),
                ('intelligence', models.IntegerField()),
                ('playfulness', models.IntegerField()),
            ],
            options={
                'db_table': 'Breed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pet_image', models.CharField(max_length=100)),
                ('pet_color', models.CharField(max_length=50)),
                ('is_adopted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adoption.pet')),
            ],
            bases=('adoption.pet',),
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adoption.pet')),
            ],
            bases=('adoption.pet',),
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adoption.pet')),
                ('other_type', models.CharField(max_length=50)),
            ],
            bases=('adoption.pet',),
        ),
    ]
