# Generated by Django 4.2.7 on 2023-12-21 18:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_admin'),
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='adoption.pet')),
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('adoption.pet',),
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='adoption.pet')),
                ('dog_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('adoption.pet',),
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='adoption.pet')),
                ('other_type', models.CharField(max_length=50)),
                ('other_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('adoption.pet',),
        ),
        migrations.CreateModel(
            name='OverseeingReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oreq_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('oreq_status', models.CharField(default='PENDING', max_length=8)),
                ('oreq_response_date', models.DateTimeField(default=None)),
                ('omotivation_text', models.TextField(default=None)),
                ('oreq_result', models.CharField(default=None, max_length=14)),
                ('adopter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.adopter')),
                ('ao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.adoptionorganization')),
            ],
            options={
                'unique_together': {('ao_id', 'adopter_id', 'oreq_date')},
            },
        ),
        migrations.CreateModel(
            name='AgreementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreq_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('agreq_status', models.CharField(default='PENDING', max_length=8)),
                ('agreq_response_date', models.DateTimeField(default=None)),
                ('agmotivation_text', models.TextField(default=None)),
                ('agreq_term_date', models.DateTimeField(default=None)),
                ('ao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.adoptionorganization')),
                ('vet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.veterinarian')),
            ],
            options={
                'unique_together': {('ao_id', 'vet_id', 'agreq_date')},
            },
        ),
    ]
